//import static com.sun.xml.internal.fastinfoset.alphabet.BuiltInRestrictedAlphabets.table;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import Project.ConncetionProvider;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gagan
 */
public class BOOK_AUTHOR extends javax.swing.JFrame {

    /**
     * Creates new form BOOK_AUTHOR
     */
    public BOOK_AUTHOR() {
        initComponents();
         DefaultTableModel model=( DefaultTableModel)jTableBookAuthors.getModel();
        
        try
                {
                     Connection con=ConncetionProvider.getCon();
						String query="select * from BOOK_AUTHOR";
						PreparedStatement pst1=con.prepareStatement(query);
						ResultSet rs=pst1.executeQuery();
                    
                    while(rs.next())
                    {
                       model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3)});
                    }
                    
                }
            catch(Exception e)
                    {
                        
                    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAuthorID = new javax.swing.JLabel();
        jLabelAuthorName = new javax.swing.JLabel();
        jLabelAuthorMail = new javax.swing.JLabel();
        jTextFieldAuthorID = new javax.swing.JTextField();
        jTextFieldAuthorName = new javax.swing.JTextField();
        jTextFieldAuthorMail = new javax.swing.JTextField();
        jButtonADD = new javax.swing.JButton();
        jButtonVIEW = new javax.swing.JButton();
        jButtonRESET = new javax.swing.JButton();
        jButtonDELETE = new javax.swing.JButton();
        jButtonEXIT = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableBookAuthors = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 200));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelAuthorID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelAuthorID.setText("AUTHOR ID");
        getContentPane().add(jLabelAuthorID, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        jLabelAuthorName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelAuthorName.setText("AUTHOR NAME");
        getContentPane().add(jLabelAuthorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        jLabelAuthorMail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelAuthorMail.setText("AUTHOR MAIL ");
        getContentPane().add(jLabelAuthorMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));

        jTextFieldAuthorID.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(jTextFieldAuthorID, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 200, -1));

        jTextFieldAuthorName.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldAuthorName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAuthorNameActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldAuthorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 200, -1));

        jTextFieldAuthorMail.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldAuthorMail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldAuthorMailKeyReleased(evt);
            }
        });
        getContentPane().add(jTextFieldAuthorMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 200, -1));

        jButtonADD.setBackground(new java.awt.Color(255, 255, 204));
        jButtonADD.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonADD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        jButtonADD.setText("ADD");
        jButtonADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonADDActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonADD, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, -1, -1));

        jButtonVIEW.setBackground(new java.awt.Color(255, 255, 204));
        jButtonVIEW.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonVIEW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view.png"))); // NOI18N
        jButtonVIEW.setText("VIEW");
        jButtonVIEW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVIEWActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVIEW, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 470, -1, -1));

        jButtonRESET.setBackground(new java.awt.Color(255, 255, 204));
        jButtonRESET.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonRESET.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reset.png"))); // NOI18N
        jButtonRESET.setText("RESET");
        jButtonRESET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRESETActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRESET, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 470, -1, -1));

        jButtonDELETE.setBackground(new java.awt.Color(255, 255, 204));
        jButtonDELETE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDELETE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        jButtonDELETE.setText("DELETE");
        jButtonDELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDELETEActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDELETE, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 470, -1, -1));

        jButtonEXIT.setBackground(new java.awt.Color(255, 255, 204));
        jButtonEXIT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonEXIT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit1.png"))); // NOI18N
        jButtonEXIT.setText("EXIT");
        jButtonEXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEXITActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEXIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 470, -1, -1));

        jTableBookAuthors.setBackground(new java.awt.Color(255, 255, 204));
        jTableBookAuthors.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTableBookAuthors.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "AUTHOR _ID", "AUTHOR_NAME", "AUTHOR_MAIL"
            }
        ));
        jScrollPane1.setViewportView(jTableBookAuthors);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 521, 200));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/123456.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldAuthorNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAuthorNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAuthorNameActionPerformed

    private void jButtonADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonADDActionPerformed
        // TODO add your handling code here:
         String authorname = jTextFieldAuthorName.getText();
	 String authormail_id= jTextFieldAuthorMail.getText();
	 String author_id = jTextFieldAuthorID.getText();
          if(authormail_id.matches("^[_a-za-z0-9-]+(\\.[_a-za-z0-9-]+)*@[a-za-z0-9-]+(\\.[a-za-z0-9-]+)*(\\.[a-za-z]{2,})$"))
         {
            
       
             
        try {
				        Class.forName("oracle.jdbc.driver.OracleDriver");
				        Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "disha", "gagan");
				        
				        String sql = "Insert Into BOOK_AUTHOR values('"+author_id+"','"+authorname+"','"+authormail_id+"')";
				        PreparedStatement pst=con.prepareStatement(sql);
				        ResultSet rs=pst.executeQuery();
				        JOptionPane.showMessageDialog(null,"Data Inserted Successfully");
                                        
				       		       
				    } catch(Exception e) {System.out.println(e);
                                      JOptionPane.showMessageDialog(null,"enter data is incorrect please check once \n * Authorid exist * Authorid invalid (Check the format of Author_id ) * Mailid invalid ");
				}
          }
         else
         {
            
              JOptionPane.showMessageDialog(null,"enter data is incorrect please check once \n * Authorid exist \n * Authorid invalid (Check the format of Author_id ) \n * Mailid invalid ");
         }
         
    }//GEN-LAST:event_jButtonADDActionPerformed

    private void jButtonVIEWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVIEWActionPerformed
        // TODO add your handling code here:
        try 
				{
                                        Connection con=ConncetionProvider.getCon();
					String query="select * from BOOK_AUTHOR";
					PreparedStatement pst1=con.prepareStatement(query);
					ResultSet rs=pst1.executeQuery();
					jTableBookAuthors.setModel(DbUtils.resultSetToTableModel(rs));
				}
				catch (Exception e) 
				{
					e.printStackTrace();
				}
    }//GEN-LAST:event_jButtonVIEWActionPerformed

    private void jButtonRESETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRESETActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null,"Data Reset Successfull");
                        jTextFieldAuthorID.setText(null);
			jTextFieldAuthorMail.setText(null);
			jTextFieldAuthorName.setText(null);
    }//GEN-LAST:event_jButtonRESETActionPerformed

    private void jButtonDELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDELETEActionPerformed
        // TODO add your handling code here:
        int row = jTableBookAuthors.getSelectedRow();
				System.out.println(row);
				String cell = jTableBookAuthors.getModel().getValueAt(row, 0).toString();
				String query="delete from BOOK_AUTHOR where AUTHOR_ID='"+cell+"'";
				System.out.println(query);
                                
                                try 
				{
                                        Connection con=ConncetionProvider.getCon();
					PreparedStatement pst2=con.prepareStatement(query);
					pst2.executeQuery();
					JOptionPane.showMessageDialog(null,"Row Deleted Successful");
				}
				catch (Exception e) 
				{
					e.printStackTrace();
				}
    }//GEN-LAST:event_jButtonDELETEActionPerformed

    private void jButtonEXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEXITActionPerformed
        // TODO add your handling code here:
         setVisible(false);
    }//GEN-LAST:event_jButtonEXITActionPerformed

    private void jTextFieldAuthorMailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAuthorMailKeyReleased
        // TODO add your handling code here:
   
    }//GEN-LAST:event_jTextFieldAuthorMailKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BOOK_AUTHOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BOOK_AUTHOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BOOK_AUTHOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BOOK_AUTHOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BOOK_AUTHOR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonADD;
    private javax.swing.JButton jButtonDELETE;
    private javax.swing.JButton jButtonEXIT;
    private javax.swing.JButton jButtonRESET;
    private javax.swing.JButton jButtonVIEW;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelAuthorID;
    private javax.swing.JLabel jLabelAuthorMail;
    private javax.swing.JLabel jLabelAuthorName;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableBookAuthors;
    private javax.swing.JTextField jTextFieldAuthorID;
    private javax.swing.JTextField jTextFieldAuthorMail;
    private javax.swing.JTextField jTextFieldAuthorName;
    // End of variables declaration//GEN-END:variables
}
