/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gagan
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonBookAutor = new javax.swing.JButton();
        jButtonBooks = new javax.swing.JButton();
        jButtonCUSTOMER = new javax.swing.JButton();
        jButtonRATING = new javax.swing.JButton();
        jButtonLOGOUT = new javax.swing.JButton();
        jButtonPAYMENT = new javax.swing.JButton();
        jButtonPURCHASE = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonBookAutor.setBackground(new java.awt.Color(153, 255, 255));
        jButtonBookAutor.setFont(new java.awt.Font("Colonna MT", 1, 19)); // NOI18N
        jButtonBookAutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Book author.png"))); // NOI18N
        jButtonBookAutor.setText("BOOK AUTHOR");
        jButtonBookAutor.setPreferredSize(new java.awt.Dimension(199, 59));
        jButtonBookAutor.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButtonBookAutorMouseMoved(evt);
            }
        });
        jButtonBookAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBookAutorActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBookAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 220, -1));

        jButtonBooks.setBackground(new java.awt.Color(102, 255, 204));
        jButtonBooks.setFont(new java.awt.Font("Colonna MT", 1, 19)); // NOI18N
        jButtonBooks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New book.png"))); // NOI18N
        jButtonBooks.setText("BOOKS");
        jButtonBooks.setPreferredSize(new java.awt.Dimension(199, 59));
        jButtonBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBooksActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 220, -1));

        jButtonCUSTOMER.setBackground(new java.awt.Color(51, 153, 255));
        jButtonCUSTOMER.setFont(new java.awt.Font("Colonna MT", 1, 19)); // NOI18N
        jButtonCUSTOMER.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer.png"))); // NOI18N
        jButtonCUSTOMER.setText("CUSTOMER");
        jButtonCUSTOMER.setPreferredSize(new java.awt.Dimension(199, 49));
        jButtonCUSTOMER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCUSTOMERActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCUSTOMER, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, 220, 60));

        jButtonRATING.setBackground(new java.awt.Color(255, 153, 153));
        jButtonRATING.setFont(new java.awt.Font("Colonna MT", 1, 19)); // NOI18N
        jButtonRATING.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rating.png"))); // NOI18N
        jButtonRATING.setText("FEEDBACK");
        jButtonRATING.setPreferredSize(new java.awt.Dimension(199, 49));
        jButtonRATING.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRATINGActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRATING, new org.netbeans.lib.awtextra.AbsoluteConstraints(1570, 30, 220, 60));

        jButtonLOGOUT.setBackground(new java.awt.Color(153, 255, 102));
        jButtonLOGOUT.setFont(new java.awt.Font("Colonna MT", 1, 19)); // NOI18N
        jButtonLOGOUT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
        jButtonLOGOUT.setText("LOGOUT");
        jButtonLOGOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLOGOUTActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLOGOUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 860, 220, -1));

        jButtonPAYMENT.setBackground(new java.awt.Color(255, 153, 0));
        jButtonPAYMENT.setFont(new java.awt.Font("Colonna MT", 1, 19)); // NOI18N
        jButtonPAYMENT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payment.png"))); // NOI18N
        jButtonPAYMENT.setText("PAYMENT");
        jButtonPAYMENT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPAYMENTActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPAYMENT, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 30, 210, 59));

        jButtonPURCHASE.setBackground(new java.awt.Color(255, 255, 0));
        jButtonPURCHASE.setFont(new java.awt.Font("Colonna MT", 1, 18)); // NOI18N
        jButtonPURCHASE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/return-book-1-560407.png"))); // NOI18N
        jButtonPURCHASE.setText("PURCHASE DETAILS");
        jButtonPURCHASE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPURCHASEActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPURCHASE, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 30, 230, 60));

        jButton1.setBackground(new java.awt.Color(204, 153, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EXIT2.png"))); // NOI18N
        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1710, 990, 170, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, -1, 1140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLOGOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLOGOUTActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new login().setVisible(true);
    }//GEN-LAST:event_jButtonLOGOUTActionPerformed

    private void jButtonBookAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBookAutorActionPerformed
        // TODO add your handling code here:
        new BOOK_AUTHOR().setVisible(true);
    }//GEN-LAST:event_jButtonBookAutorActionPerformed

    private void jButtonBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBooksActionPerformed
        // TODO add your handling code here:
          new BOOKS().setVisible(true);
        
    }//GEN-LAST:event_jButtonBooksActionPerformed

    private void jButtonCUSTOMERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCUSTOMERActionPerformed
        // TODO add your handling code here:
        new CUSTOMER().setVisible(true);
    }//GEN-LAST:event_jButtonCUSTOMERActionPerformed

    private void jButtonPAYMENTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPAYMENTActionPerformed
        // TODO add your handling code here:
         new PAYMENT().setVisible(true);
    }//GEN-LAST:event_jButtonPAYMENTActionPerformed

    private void jButtonRATINGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRATINGActionPerformed
        // TODO add your handling code here:
         new RATING().setVisible(true);
    }//GEN-LAST:event_jButtonRATINGActionPerformed

    private void jButtonBookAutorMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBookAutorMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBookAutorMouseMoved

    private void jButtonPURCHASEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPURCHASEActionPerformed
        // TODO add your handling code here:
        new PURCHASE().setVisible(true);
    }//GEN-LAST:event_jButtonPURCHASEActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBookAutor;
    private javax.swing.JButton jButtonBooks;
    private javax.swing.JButton jButtonCUSTOMER;
    private javax.swing.JButton jButtonLOGOUT;
    private javax.swing.JButton jButtonPAYMENT;
    private javax.swing.JButton jButtonPURCHASE;
    private javax.swing.JButton jButtonRATING;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
