import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import Project.ConncetionProvider;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gagan
 */
public class RATING extends javax.swing.JFrame {

    /**
     * Creates new form RATING
     */
    public RATING() {
        initComponents();
         DefaultTableModel model=( DefaultTableModel)jTableRATING.getModel();
        
        try
                {
                     Connection con=ConncetionProvider.getCon();
						String query="select * from RATING";
						PreparedStatement pst1=con.prepareStatement(query);
						ResultSet rs=pst1.executeQuery();
                    
                    while(rs.next())
                    {
                       model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3)});
                    }
                    
                }
            catch(Exception e)
                    {
                        
                    }
        
         DefaultTableModel mode2=( DefaultTableModel)jTableCUSTOMER.getModel();
        
        try
                {
                     Connection con=ConncetionProvider.getCon();
						String query="select CUSTOMER_ID,CUSTOMER_NAME from CUSTOMER";
						PreparedStatement pst1=con.prepareStatement(query);
						ResultSet rs=pst1.executeQuery();
                    
                    while(rs.next())
                    {
                       mode2.addRow(new Object[]{rs.getString(1),rs.getString(2)});
                    }
                    
                }
            catch(Exception e)
                    {
                        
                    }
        
        
      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCID = new javax.swing.JLabel();
        jLabelINSTOREEXPERIENCES = new javax.swing.JLabel();
        jLabelCUSTOMERSUPPORT = new javax.swing.JLabel();
        jTextFieldCID = new javax.swing.JTextField();
        jComboBoxINSTOREEXPERIENCES = new javax.swing.JComboBox<>();
        jButtonADD = new javax.swing.JButton();
        jButtonVIEW = new javax.swing.JButton();
        jButtonRESET = new javax.swing.JButton();
        jButtonDELETE = new javax.swing.JButton();
        jButtonEXIT = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRATING = new javax.swing.JTable();
        jTextFieldCUSTOMERSUGGESTION = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCUSTOMER = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 200));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCID.setText("CUSTOMER ID");
        getContentPane().add(jLabelCID, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabelINSTOREEXPERIENCES.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelINSTOREEXPERIENCES.setText("IN STORE EXPERIENCES");
        getContentPane().add(jLabelINSTOREEXPERIENCES, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabelCUSTOMERSUPPORT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCUSTOMERSUPPORT.setText("CUSTOMER SUGESTION");
        getContentPane().add(jLabelCUSTOMERSUPPORT, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jTextFieldCID.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(jTextFieldCID, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 200, -1));

        jComboBoxINSTOREEXPERIENCES.setBackground(new java.awt.Color(255, 255, 204));
        jComboBoxINSTOREEXPERIENCES.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EXCELLENT", "VERY GOOD", "GOOD", "NOT BAD", "BAD" }));
        getContentPane().add(jComboBoxINSTOREEXPERIENCES, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 200, -1));

        jButtonADD.setBackground(new java.awt.Color(255, 255, 204));
        jButtonADD.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonADD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        jButtonADD.setText("ADD");
        jButtonADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonADDActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonADD, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        jButtonVIEW.setBackground(new java.awt.Color(255, 255, 204));
        jButtonVIEW.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonVIEW.setForeground(new java.awt.Color(51, 51, 51));
        jButtonVIEW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view.png"))); // NOI18N
        jButtonVIEW.setText("VIEW");
        jButtonVIEW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVIEWActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVIEW, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, -1, -1));

        jButtonRESET.setBackground(new java.awt.Color(255, 255, 204));
        jButtonRESET.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonRESET.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reset.png"))); // NOI18N
        jButtonRESET.setText("RESET");
        jButtonRESET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRESETActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRESET, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, -1, -1));

        jButtonDELETE.setBackground(new java.awt.Color(255, 255, 204));
        jButtonDELETE.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDELETE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        jButtonDELETE.setText("DELETE");
        jButtonDELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDELETEActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDELETE, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, -1, -1));

        jButtonEXIT.setBackground(new java.awt.Color(255, 255, 204));
        jButtonEXIT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonEXIT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit1.png"))); // NOI18N
        jButtonEXIT.setText("EXIT");
        jButtonEXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEXITActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEXIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, -1, -1));

        jTableRATING.setBackground(new java.awt.Color(255, 255, 204));
        jTableRATING.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTableRATING.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CUSTOMER_ID", "IN_STORE_EXPERIENCE", "CUSTOMER_SUGGESTION"
            }
        ));
        jScrollPane1.setViewportView(jTableRATING);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 560, 216));

        jTextFieldCUSTOMERSUGGESTION.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(jTextFieldCUSTOMERSUGGESTION, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 199, -1));

        jTableCUSTOMER.setBackground(new java.awt.Color(255, 255, 204));
        jTableCUSTOMER.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTableCUSTOMER.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CUSTOMER_ID", "CUSTOMER_NAME"
            }
        ));
        jScrollPane2.setViewportView(jTableCUSTOMER);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 560, 220));

        jLabel2.setFont(new java.awt.Font("Colonna MT", 1, 18)); // NOI18N
        jLabel2.setText("FEEDBACK");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(673, 26, -1, -1));

        jLabel3.setFont(new java.awt.Font("Colonna MT", 1, 18)); // NOI18N
        jLabel3.setText("CUSTOMER");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(674, 285, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/123456.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonADDActionPerformed
        // TODO add your handling code here:
                                  String CID = jTextFieldCID.getText();
				  String INSTOREEXPERIENCES = (String)jComboBoxINSTOREEXPERIENCES.getSelectedItem();
				String CUSTOMER_SUGGESTION = jTextFieldCUSTOMERSUGGESTION.getText();
				    try {
				        Class.forName("oracle.jdbc.driver.OracleDriver");
				        Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","disha","gagan");
				       
				        String sql = "Insert Into RATING values('"+CID+"','"+INSTOREEXPERIENCES+"','"+CUSTOMER_SUGGESTION+"')";
				        PreparedStatement pst=con.prepareStatement(sql);
				        ResultSet rs=pst.executeQuery();
				        JOptionPane.showMessageDialog(null,"Data Inserted Successfully");
				       		       
				    } catch(Exception e) {System.out.println(e);
                                      JOptionPane.showMessageDialog(null," INVALID CUSTOMER ID");
				}
    }//GEN-LAST:event_jButtonADDActionPerformed

    private void jButtonVIEWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVIEWActionPerformed
        // TODO add your handling code here:
                  try 
				{
                                        Connection con=ConncetionProvider.getCon();
					String query="select * from RATING";
					PreparedStatement pst1=con.prepareStatement(query);
					ResultSet rs=pst1.executeQuery();
					jTableRATING.setModel(DbUtils.resultSetToTableModel(rs));
				}
				catch (Exception e) 
				{
					e.printStackTrace();
				}
    }//GEN-LAST:event_jButtonVIEWActionPerformed

    private void jButtonRESETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRESETActionPerformed
        // TODO add your handling code here:
             jTextFieldCID.setText(null);
             jTextFieldCUSTOMERSUGGESTION.setText(null);
				
        
    }//GEN-LAST:event_jButtonRESETActionPerformed

    private void jButtonDELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDELETEActionPerformed
        // TODO add your handling code here:
         int row = jTableRATING.getSelectedRow();
				System.out.println(row);
				String cell = jTableRATING.getModel().getValueAt(row, 0).toString();
				String query="delete from RATING where CUSTOMER_ID='"+cell+"'";
				System.out.println(query);
				
				
				try 
				{
                                        Connection con=ConncetionProvider.getCon();
					PreparedStatement pst2=con.prepareStatement(query);
					pst2.executeQuery();
					JOptionPane.showMessageDialog(null,"Row Deleted Successful");
				}
				catch (Exception e) 
				{
					e.printStackTrace();
				}
    }//GEN-LAST:event_jButtonDELETEActionPerformed

    private void jButtonEXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEXITActionPerformed
        // TODO add your handling code here:
           setVisible(false);
    }//GEN-LAST:event_jButtonEXITActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RATING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RATING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RATING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RATING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RATING().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonADD;
    private javax.swing.JButton jButtonDELETE;
    private javax.swing.JButton jButtonEXIT;
    private javax.swing.JButton jButtonRESET;
    private javax.swing.JButton jButtonVIEW;
    private javax.swing.JComboBox<String> jComboBoxINSTOREEXPERIENCES;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCID;
    private javax.swing.JLabel jLabelCUSTOMERSUPPORT;
    private javax.swing.JLabel jLabelINSTOREEXPERIENCES;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableCUSTOMER;
    private javax.swing.JTable jTableRATING;
    private javax.swing.JTextField jTextFieldCID;
    private javax.swing.JTextField jTextFieldCUSTOMERSUGGESTION;
    // End of variables declaration//GEN-END:variables
}
